// Code generated by goctl. DO NOT EDIT.
package types

type AddDeptReq struct {
	DeptName  string  `json:"deptName"`          // 机构名称
	ParentId  int64   `json:"parentId"`          // 上级机构ID，一级机构为0
	ParentIds []int64 `json:"parentIds"`         // 上级机构IDs
	OrderNum  int32   `json:"orderNum"`          // 排序
	DelFlag   int32   `json:"delFlag,default=2"` // 是否删除  0：已删除  1：正常
}

type AddDeptResp struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

type AddDictItemReq struct {
	DictLabel  string `json:"dictLabel"`  //字典标签
	DictSort   int32  `json:"dictSort"`   //排序
	DictStatus int32  `json:"dictStatus"` //字典状态
	DictType   string `json:"dictType"`   //字典类型
	DictValue  string `json:"dictValue"`  //字典键值
	Remark     string `json:"remark"`     //备注信息
}

type AddDictItemResp struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

type AddDictReq struct {
	DictName   string `json:"dictName"`   //字典名称
	DictStatus int32  `json:"dictStatus"` //字典状态
	DictType   string `json:"dictType"`   //字典类型
	IsSystem   int32  `json:"isSystem"`   //是否系统预留  0：否  1：是
	Remark     string `json:"remark"`     //备注信息
}

type AddDictResp struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

type AddJobReq struct {
	JobName  string `json:"jobName"`  // 职位名称
	Remarks  string `json:"remarks"`  // 备注
	OrderNum int32  `json:"orderNum"` // 排序
	DelFlag  int32  `json:"delFlag"`  // 是否删除  0：已删除  1：正常
}

type AddJobResp struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

type AddMenuReq struct {
	Name          string `json:"name"`                   // 菜单名称
	ParentId      int64  `json:"parentId,optional"`      // 父菜单ID，一级菜单为0
	Url           string `json:"url,optional"`           // 菜单URL,类型：1.普通页面（如用户管理， /sysmodel/user） 2.嵌套完整外部页面，以http(s)开头的链接 3.嵌套服务器页面，使用iframe:前缀+目标URL(如SQL监控， iframe:/druid/login.html, iframe:前缀会替换成服务器地址)
	Perms         string `json:"perms,optional"`         // 授权(多个用逗号分隔，如：sysmodel:user:Add,sysmodel:user:edit)
	Type          int32  `json:"type,optional"`          // 类型   0：目录   1：菜单   2：按钮
	Icon          string `json:"icon,optional"`          // 菜单图标
	OrderNum      int32  `json:"orderNum,optional"`      // 排序
	VuePath       string `json:"vuePath,optional"`       // vue系统的path
	VueComponent  string `json:"vueComponent,optional"`  // vue的页面
	VueIcon       string `json:"vueIcon,optional"`       // vue的图标
	VueRedirect   string `json:"vueRedirect,optional"`   // vue的路由重定向
	DelFlag       int32  `json:"delFlag"`                // 是否删除  0：已删除  1：正常
	BackgroundUrl string `json:"backgroundUrl,optional"` // 后台地址
}

type AddMenuResp struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

type AddRoleReq struct {
	Name   string `json:"name"`            // 角色名称
	Remark string `json:"remark,optional"` // 备注
	Status int32  `json:"status"`          // 状态
}

type AddRoleResp struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

type AddUserReq struct {
	Email    string `json:"email"`
	Mobile   string `json:"mobile"`
	Name     string `json:"name"`
	NickName string `json:"nickName"`
	DeptId   int64  `json:"deptId"`
	JobId    int64  `json:"jobId"`
	Status   int32  `json:"status"` // 状态  0：禁用   1：正常
}

type AddUserResp struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

type DeleteDeptReq struct {
	Ids []int64 `form:"ids"`
}

type DeleteDeptResp struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

type DeleteDictItemReq struct {
	Ids []int64 `form:"ids"`
}

type DeleteDictItemResp struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

type DeleteDictReq struct {
	Ids []int64 `form:"ids"`
}

type DeleteDictResp struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

type DeleteJobReq struct {
	Ids []int64 `form:"ids"`
}

type DeleteJobResp struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

type DeleteLoginLogReq struct {
	Ids []int64 `form:"ids"`
}

type DeleteLoginLogResp struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

type DeleteMenuReq struct {
	Ids []int64 `form:"ids"`
}

type DeleteMenuResp struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

type DeleteRoleReq struct {
	Ids []int64 `form:"ids"`
}

type DeleteRoleResp struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

type DeleteSysLogReq struct {
	Ids []int64 `form:"ids"`
}

type DeleteSysLogResp struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

type DeleteUserReq struct {
	Ids []int64 `form:"ids"`
}

type DeleteUserResp struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

type DeptRelations struct {
	Id       int64  `json:"id"`
	Value    string `json:"value"`
	Title    string `json:"title"`
	ParentId int64  `json:"parentId"`
}

type JobRelations struct {
	Id      int64  `json:"id"`
	JobName string `json:"jobName"`
}

type ListDeptData struct {
	Id         int64   `json:"id"`         // 编号
	DeptName   string  `json:"deptName"`   // 机构名称
	ParentId   int64   `json:"parentId"`   // 上级机构ID，一级机构为0
	ParentIds  []int64 `json:"parentIds"`  // 上级机构ID
	OrderNum   int32   `json:"orderNum"`   // 排序
	CreateBy   string  `json:"createBy"`   // 创建人
	CreateTime string  `json:"createTime"` // 创建时间
	UpdateBy   string  `json:"updateBy"`   // 更新人
	UpdateTime string  `json:"updateTime"` // 更新时间
	DelFlag    int32   `json:"delFlag"`    // 是否删除  0：已删除  1：正常
}

type ListDeptReq struct {
	Name     string `json:"form,optional"`
	CreateBy string `json:"form,optional"`
}

type ListDeptResp struct {
	Code    string          `json:"code"`
	Message string          `json:"message"`
	Data    []*ListDeptData `json:"data"`
	Success bool            `json:"success"`
}

type ListDictData struct {
	CreateBy   string `json:"createBy"`   //创建者
	CreateTime string `json:"createTime"` //创建时间
	DelFlag    int32  `json:"delFlag"`    //是否删除  1：已删除  0：正常
	DictName   string `json:"dictName"`   //字典名称
	DictStatus int32  `json:"dictStatus"` //字典状态
	DictType   string `json:"dictType"`   //字典类型
	Id         int64  `json:"id"`         //编号
	IsSystem   int32  `json:"isSystem"`   //是否系统预留  0：否  1：是
	Remark     string `json:"remark"`     //备注信息
	UpdateBy   string `json:"updateBy"`   //更新者
	UpdateTime string `json:"updateTime"` //更新时间
}

type ListDictItemData struct {
	CreateBy   string `json:"createBy"`   //创建者
	CreateTime string `json:"createTime"` //创建时间
	DelFlag    int32  `json:"delFlag"`    //是否删除  1：已删除  0：正常
	DictLabel  string `json:"dictLabel"`  //字典标签
	DictSort   int32  `json:"dictSort"`   //排序
	DictStatus int32  `json:"dictStatus"` //字典状态
	DictType   string `json:"dictType"`   //字典类型
	DictValue  string `json:"dictValue"`  //字典键值
	Id         int64  `json:"id"`         //编号
	IsDefault  int32  `json:"isDefault"`  //是否默认  0：否  1：是
	Remark     string `json:"remark"`     //备注信息
	UpdateBy   string `json:"updateBy"`   //更新者
	UpdateTime string `json:"updateTime"` //更新时间
}

type ListDictItemReq struct {
	Current    int64  `form:"current,default=1"`
	PageSize   int64  `form:"pageSize,default=20"`
	DictLabel  string `form:"dictLabel,optional"`   //字典标签
	DictStatus int32  `form:"dictStatus,default=2"` //字典状态
	DictType   string `form:"dictType,optional"`    //字典类型
}

type ListDictItemResp struct {
	Code     string              `json:"code"`
	Message  string              `json:"message"`
	Current  int64               `json:"current,default=1"`
	Data     []*ListDictItemData `json:"data"`
	PageSize int64               `json:"pageSize,default=20"`
	Success  bool                `json:"success"`
	Total    int64               `json:"total"`
}

type ListDictReq struct {
	Current    int64  `form:"current,default=1"`
	PageSize   int64  `form:"pageSize,default=20"`
	DictName   string `form:"dictName,optional"`    //字典名称
	DictStatus int32  `form:"dictStatus,default=2"` //字典状态
	DictType   string `form:"dictType,optional"`    //字典类型
	IsSystem   int32  `form:"isSystem,optional"`    //是否系统预留  0：否  1：是
}

type ListDictResp struct {
	Code     string          `json:"code"`
	Message  string          `json:"message"`
	Current  int64           `json:"current,default=1"`
	Data     []*ListDictData `json:"data"`
	PageSize int64           `json:"pageSize,default=20"`
	Success  bool            `json:"success"`
	Total    int64           `json:"total"`
}

type ListJobData struct {
	Id         int64  `json:"id"`         // 编号
	JobName    string `json:"jobName"`    // 职位名称
	OrderNum   int32  `json:"orderNum"`   // 排序
	CreateBy   string `json:"createBy"`   // 创建人
	CreateTime string `json:"createTime"` // 创建时间
	UpdateBy   string `json:"updateBy"`   // 更新人
	UpdateTime string `json:"updateTime"` // 更新时间
	DelFlag    int32  `json:"delFlag"`    // 是否删除  0：已删除  1：正常
	Remarks    string `json:"remarks"`    // 备注
}

type ListJobReq struct {
	Current  int64  `form:"current,default=1"`
	PageSize int64  `form:"pageSize,default=20"`
	JobName  string `form:"jobName,optional"`
	DelFlag  int32  `form:"delFlag,default=2"` // 是否删除  0：已删除  1：正常
}

type ListJobResp struct {
	Code     string         `json:"code"`
	Message  string         `json:"message"`
	Current  int64          `json:"current,default=1"`
	Data     []*ListJobData `json:"data"`
	PageSize int64          `json:"pageSize,default=20"`
	Success  bool           `json:"success"`
	Total    int64          `json:"total"`
}

type ListLoginLogData struct {
	Id         int64  `json:"id"`         // 编号
	UserName   string `json:"userName"`   // 用户名
	Status     string `json:"status"`     // 登录状态（online:在线，登录初始状态，方便统计在线人数；login:退出登录后将online置为login；logout:退出登录）
	Ip         string `json:"ip"`         // IP地址
	CreateBy   string `json:"createBy"`   // 创建人
	CreateTime string `json:"createTime"` // 创建时间
	UpdateBy   string `json:"updateBy"`   // 更新人
	UpdateTime string `json:"updateTime"` // 更新时间
}

type ListLoginLogReq struct {
	Current  int64  `form:"current,default=1"`
	PageSize int64  `form:"pageSize,default=20"`
	UserName string `form:"userName,optional"`
	Ip       string `form:"ip,optional"` // IP地址
}

type ListLoginLogResp struct {
	Code     string              `json:"code"`
	Message  string              `json:"message"`
	Current  int64               `json:"current,default=1"`
	Data     []*ListLoginLogData `json:"data"`
	PageSize int64               `json:"pageSize,default=20"`
	Success  bool                `json:"success"`
	Total    int64               `json:"total"`
}

type ListMenuData struct {
	Id            int64  `json:"id"`            // 编号
	Key           string `json:"key"`           // 菜单名称
	Name          string `json:"name"`          // 菜单名称
	Title         string `json:"title"`         // 菜单名称
	ParentId      int64  `json:"parentId"`      // 父菜单ID，一级菜单为0
	Url           string `json:"url"`           // 菜单URL,类型：1.普通页面（如用户管理， /sysmodel/user） 2.嵌套完整外部页面，以http(s)开头的链接 3.嵌套服务器页面，使用iframe:前缀+目标URL(如SQL监控， iframe:/druid/login.html, iframe:前缀会替换成服务器地址)
	Perms         string `json:"perms"`         // 授权(多个用逗号分隔，如：sysmodel:user:Add,sysmodel:user:edit)
	Type          int32  `json:"type"`          // 类型   0：目录   1：菜单   2：按钮
	Icon          string `json:"icon"`          // 菜单图标
	OrderNum      int32  `json:"orderNum"`      // 排序
	CreateBy      string `json:"createBy"`      // 创建人
	CreateTime    string `json:"createTime"`    // 创建时间
	UpdateBy      string `json:"updateBy"`      // 更新人
	UpdateTime    string `json:"updateTime"`    // 更新时间
	DelFlag       int32  `json:"delFlag"`       // 是否删除  0：已删除  1：正常
	VuePath       string `json:"vuePath"`       // vue系统的path
	VueComponent  string `json:"vueComponent"`  // vue的页面
	VueIcon       string `json:"vueIcon"`       // vue的图标
	VueRedirect   string `json:"vueRedirect"`   // vue的路由重定向
	BackgroundUrl string `json:"backgroundUrl"` // 后台地址
}

type ListMenuReq struct {
	Name string `form:"name,optional"`
	Url  string `form:"url,optional "`
}

type ListMenuResp struct {
	Code    string          `json:"code"`
	Message string          `json:"message"`
	Data    []*ListMenuData `json:"data"`
	Success bool            `json:"success"`
	Total   int64           `json:"total"`
}

type ListMenuTree struct {
	Id       int64  `json:"id"`       // 编号
	Path     string `json:"path"`     // 菜单路径
	Name     string `json:"name"`     // 菜单名称
	ParentId int64  `json:"parentId"` // 父菜单ID，一级菜单为0
	Icon     string `json:"icon"`     // 菜单图标
}

type ListMenuTreeVue struct {
	Id           int64        `json:"id"`
	ParentId     int64        `json:"parentId"`
	Title        string       `json:"title"`
	Path         string       `json:"path"`
	Name         string       `json:"name"`
	Icon         string       `json:"icon"`
	VueRedirect  string       `json:"redirect"`
	VueComponent string       `json:"component"`
	Meta         MenuTreeMeta `json:"meta"`
}

type ListRoleData struct {
	Id         int64  `json:"id"`         // 编号
	Name       string `json:"name"`       // 角色名称
	Remark     string `json:"remark"`     // 备注
	CreateBy   string `json:"createBy"`   // 创建人
	CreateTime string `json:"createTime"` // 创建时间
	UpdateBy   string `json:"updateBy"`   // 更新人
	UpdateTime string `json:"updateTime"` // 更新时间
	DelFlag    int32  `json:"delFlag"`    // 是否删除  0：已删除  1：正常
	Label      string `json:"label"`      // 编号
	Value      string `json:"value"`      // 角色名称
	Status     int32  `json:"status"`     // 状态
}

type ListRoleReq struct {
	Current  int64  `form:"current,default=1"`
	PageSize int64  `form:"pageSize,default=20"`
	Name     string `form:"name,optional "`
	Status   int32  `form:"status,default=2"`
}

type ListRoleResp struct {
	Code     string          `json:"code"`
	Message  string          `json:"message"`
	Current  int64           `json:"current,default=1"`
	Data     []*ListRoleData `json:"data"`
	PageSize int64           `json:"pageSize,default=20"`
	Success  bool            `json:"success"`
	Total    int64           `json:"total"`
}

type ListSysLogData struct {
	Id             int64  `json:"id"`             // 编号
	UserName       string `json:"userName"`       // 用户名
	Operation      string `json:"operation"`      // 用户操作
	Method         string `json:"method"`         // 请求方法
	RequestParams  string `json:"requestParams"`  // 请求参数
	ResponseParams string `json:"responseParams"` // 响应参数
	Time           int64  `json:"time"`           // 执行时长(毫秒)
	Ip             string `json:"ip"`             // IP地址
	OperationTime  string `json:"operationTime"`  // 操作时间
}

type ListSysLogReq struct {
	Current  int64  `form:"current,default=1"`
	PageSize int64  `form:"pageSize,default=20"`
	UserName string `form:"userName,optional"` // 用户名
	Method   string `form:"method,optional"`   // 请求方法
}

type ListSysLogResp struct {
	Code     string            `json:"code"`
	Message  string            `json:"message"`
	Current  int64             `json:"current,default=1"`
	Data     []*ListSysLogData `json:"data"`
	PageSize int64             `json:"pageSize,default=20"`
	Success  bool              `json:"success"`
	Total    int64             `json:"total"`
}

type ListUserData struct {
	Id         int64  `json:"id"`         // 编号
	UserName   string `json:"name"`       // 用户名
	NickName   string `json:"nickName"`   // 昵称
	Avatar     string `json:"avatar"`     // 头像
	Email      string `json:"email"`      // 邮箱
	Mobile     string `json:"mobile"`     // 手机号
	UserStatus int32  `json:"status"`     // 状态  0：禁用   1：正常
	DeptId     int64  `json:"deptId"`     // 机构ID
	CreateBy   string `json:"createBy"`   // 创建人
	CreateTime string `json:"createTime"` // 创建时间
	UpdateBy   string `json:"updateBy"`   // 更新人
	UpdateTime string `json:"updateTime"` // 更新时间
	DelFlag    int32  `json:"delFlag"`    // 是否删除  0：已删除  1：正常
	JobId      int64  `json:"jobId"`
}

type ListUserReq struct {
	Current  int64  `form:"current,default=1"`
	PageSize int64  `form:"pageSize,default=20"`
	Name     string `form:"name,optional"`
	NickName string `form:"nickName,optional"`
	Mobile   string `form:"mobile,optional"`
	Email    string `form:"email,optional"`
	Status   int32  `form:"status,default=2"`
	DeptId   int64  `form:"deptId,optional"`
	JobId    int64  `form:"deptId,optional"`
}

type ListUserResp struct {
	Code     string          `json:"code"`
	Message  string          `json:"message"`
	Current  int64           `json:"current,default=1"`
	Data     []*ListUserData `json:"data"`
	PageSize int64           `json:"pageSize,default=20"`
	Success  bool            `json:"success"`
	Total    int64           `json:"total"`
}

type LoginData struct {
	AccessToken string `json:"token"`
}

type LoginReq struct {
	Account  string `json:"account"` //手机号或者用户名
	Password string `json:"password"`
}

type LoginResp struct {
	Code    string    `json:"code"`
	Message string    `json:"message"`
	Data    LoginData `json:"data"`
}

type MenuTreeListData struct {
	Key      string `json:"key"`      // 菜单名称
	Title    string `json:"title"`    // 菜单名称
	ParentId int64  `json:"parentId"` // 父菜单ID，一级菜单为0
	Id       int64  `json:"id"`       // 父菜单ID，一级菜单为0
	Label    string `json:"label"`    // 父菜单ID，一级菜单为0
}

type MenuTreeMeta struct {
	Title string `json:"title"`
	Icon  string `json:"icon"`
}

type QueryAllRelationsData struct {
	RoleRelations []*RoleRelations `json:"roleRelations"`
	DeptRelations []*DeptRelations `json:"deptRelations"`
	JobRelations  []*JobRelations  `json:"jobRelations"`
}

type QueryAllRelationsReq struct {
	Current  int64 `form:"current,default=1"`
	PageSize int64 `form:"pageSize,default=20"`
}

type QueryAllRelationsResp struct {
	Code    string                `json:"code"`
	Message string                `json:"message"`
	Data    QueryAllRelationsData `json:"data"`
}

type QueryRoleMenuListReq struct {
	RoleId int64 `form:"roleId"`
}

type QueryRoleMenuListResp struct {
	Code    string           `json:"code"`
	Message string           `json:"message"`
	Data    RoleMenuListData `json:"data"`
}

type QueryUserRoleListReq struct {
	UserId   int64  `form:"userId"`
	Current  int64  `form:"current,default=1"`
	PageSize int64  `form:"pageSize,default=20"`
	RoleName string `json:"roleName,optional"` // 角色名称
}

type QueryUserRoleListResp struct {
	Code    string           `json:"code"`
	Message string           `json:"message"`
	Data    UserRoleListData `json:"data"`
}

type ReSetPasswordReq struct {
	Id int64 `json:"id"`
}

type ReSetPasswordResp struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

type RoleListData struct {
	Id         int64  `json:"id"`         // 编号
	Name       string `json:"name"`       // 角色名称
	Remark     string `json:"remark"`     // 备注
	CreateBy   string `json:"createBy"`   // 创建人
	CreateTime string `json:"createTime"` // 创建时间
	UpdateBy   string `json:"updateBy"`   // 更新人
	UpdateTime string `json:"updateTime"` // 更新时间
	DelFlag    int32  `json:"delFlag"`    // 是否删除  0：已删除  1：正常
	Status     int32  `json:"status"`     // 状态
}

type RoleMenuListData struct {
	MenuList []MenuTreeListData `json:"menuList"`
	MenuIds  []int64            `json:"menuIds"`
}

type RoleRelations struct {
	Id     int64  `json:"id"`
	Name   string `json:"name"`
	Remark string `json:"remark"`
}

type StatisticsLoginLogData struct {
	DayLoginCount   int32 `json:"dayLoginCount"`   //查询当天登录人数（根据IP）
	WeekLoginCount  int32 `json:"weekLoginCount"`  //统计当前周登录人数（根据IP）
	MonthLoginCount int32 `json:"monthLoginCount"` //统计当前月登录人数（根据IP）
}

type StatisticsLoginLogReq struct {
}

type StatisticsLoginLogResp struct {
	Code    string                 `json:"code"`
	Message string                 `json:"message"`
	Data    StatisticsLoginLogData `json:"data"`
}

type UpdateDeptReq struct {
	Id        int64   `json:"id"`                // 编号
	DeptName  string  `json:"deptName"`          // 机构名称
	ParentId  int64   `json:"parentId"`          // 上级机构ID，一级机构为0
	ParentIds []int64 `json:"parentIds"`         // 上级机构ID
	OrderNum  int32   `json:"orderNum"`          // 排序
	DelFlag   int32   `json:"delFlag,default=2"` // 是否删除  0：已删除  1：正常
}

type UpdateDeptResp struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

type UpdateDictItemReq struct {
	DictLabel  string `json:"dictLabel"`  //字典标签
	DictSort   int32  `json:"dictSort"`   //排序
	DictStatus int32  `json:"dictStatus"` //字典状态
	DictType   string `json:"dictType"`   //字典类型
	DictValue  string `json:"dictValue"`  //字典键值
	Id         int64  `json:"id"`         //编号
	IsDefault  int32  `json:"isDefault"`  //是否默认  0：否  1：是
	Remark     string `json:"remark"`     //备注信息
}

type UpdateDictItemResp struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

type UpdateDictReq struct {
	DictName   string `json:"dictName"`   //字典名称
	DictStatus int32  `json:"dictStatus"` //字典状态
	DictType   string `json:"dictType"`   //字典类型
	Id         int64  `json:"id"`         //编号
	IsSystem   int32  `json:"isSystem"`   //是否系统预留  0：否  1：是
	Remark     string `json:"remark"`     //备注信息
}

type UpdateDictResp struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

type UpdateJobReq struct {
	Id       int64  `json:"id"`       // 编号
	JobName  string `json:"jobName"`  // 职位名称
	OrderNum int32  `json:"orderNum"` // 排序
	Remarks  string `json:"remarks"`  // 备注
	DelFlag  int32  `json:"delFlag"`  // 是否删除  0：已删除  1：正常
}

type UpdateJobResp struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

type UpdateMenuReq struct {
	Id            int64  `json:"id"`                     // 编号
	Name          string `json:"name"`                   // 菜单名称
	ParentId      int64  `json:"parentId"`               // 父菜单ID，一级菜单为0
	Url           string `json:"url,optional"`           // 菜单URL,类型：1.普通页面（如用户管理， /sysmodel/user） 2.嵌套完整外部页面，以http(s)开头的链接 3.嵌套服务器页面，使用iframe:前缀+目标URL(如SQL监控， iframe:/druid/login.html, iframe:前缀会替换成服务器地址)
	Perms         string `json:"perms,optional"`         // 授权(多个用逗号分隔，如：sysmodel:user:Add,sysmodel:user:edit)
	Type          int32  `json:"type,optional"`          // 类型   0：目录   1：菜单   2：按钮
	Icon          string `json:"icon,optional"`          // 菜单图标
	OrderNum      int32  `json:"orderNum,optional"`      // 排序
	VuePath       string `json:"vuePath,optional"`       // vue系统的path
	VueComponent  string `json:"vueComponent,optional"`  // vue的页面
	VueIcon       string `json:"vueIcon,optional"`       // vue的图标
	VueRedirect   string `json:"vueRedirect,optional"`   // vue的路由重定向
	DelFlag       int32  `json:"delFlag"`                // 是否删除  0：已删除  1：正常
	BackgroundUrl string `json:"backgroundUrl,optional"` // 后台地址
}

type UpdateMenuResp struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

type UpdateRoleMenuListReq struct {
	RoleId  int64   `json:"roleId"`
	MenuIds []int64 `json:"menuIds"`
}

type UpdateRoleMenuListResp struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

type UpdateRoleReq struct {
	Id     int64  `json:"id"`     // 编号
	Name   string `json:"name"`   // 角色名称
	Remark string `json:"remark"` // 备注
	Status int32  `json:"status"` // 状态
}

type UpdateRoleResp struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

type UpdateUserReq struct {
	Id       int64  `json:"id"`
	Email    string `json:"email"`
	Mobile   string `json:"mobile"`
	Name     string `json:"name"`
	NickName string `json:"nickName"`
	DeptId   int64  `json:"deptId"`
	Status   int32  `json:"status"`
	JobId    int64  `json:"jobId"`
	DelFlag  int64  `json:"delFlag,default=2"` // 是否删除  0：已删除  1：正常
}

type UpdateUserResp struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

type UpdateUserRoleReq struct {
	UserId  int64   `json:"userId"`
	RoleIds []int64 `json:"roleIds"`
}

type UpdateUserRoleResp struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

type UploadResp struct {
	Code    string `json:"code"`
	Message string `json:"message"`
	Data    string `json:"data"`
}

type UserInfoData struct {
	Avatar      string             `json:"avatar"`
	Name        string             `json:"name"`
	MenuTree    []*ListMenuTree    `json:"menuTree"`
	MenuTreeVue []*ListMenuTreeVue `json:"menuTreeVue"`
}

type UserRoleListData struct {
	RoleList []RoleListData `json:"roleList"`
	RoleIds  []int64        `json:"roleIds"`
}

type UserStatusReq struct {
	Id     int64 `json:"id"`
	Status int32 `json:"status"` // 状态  0：禁用   1：正常
}

type UserStatusResp struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

type UserInfoResp struct {
	Code    string       `json:"code"`
	Message string       `json:"message"`
	Data    UserInfoData `json:"data"`
}
