// Code generated by goctl. DO NOT EDIT.
package types

type AddUserReq struct {
	Email    string `json:"email"`
	Mobile   string `json:"mobile"`
	Name     string `json:"name"`
	NickName string `json:"nickName"`
	DeptId   int64  `json:"deptId"`
	JobId    int64  `json:"jobId"`
	Status   int32  `json:"status"` // 状态  0：禁用   1：正常
}

type AddUserResp struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

type DeleteUserReq struct {
	Ids []int64 `form:"ids"`
}

type DeleteUserResp struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

type DeptRelations struct {
	Id       int64  `json:"id"`
	Value    string `json:"value"`
	Title    string `json:"title"`
	ParentId int64  `json:"parentId"`
}

type JobRelations struct {
	Id      int64  `json:"id"`
	JobName string `json:"jobName"`
}

type ListMenuTree struct {
	Id       int64  `json:"id"`       // 编号
	Path     string `json:"path"`     // 菜单路径
	Name     string `json:"name"`     // 菜单名称
	ParentId int64  `json:"parentId"` // 父菜单ID，一级菜单为0
	Icon     string `json:"icon"`     // 菜单图标
}

type ListMenuTreeVue struct {
	Id           int64        `json:"id"`
	ParentId     int64        `json:"parentId"`
	Title        string       `json:"title"`
	Path         string       `json:"path"`
	Name         string       `json:"name"`
	Icon         string       `json:"icon"`
	VueRedirect  string       `json:"redirect"`
	VueComponent string       `json:"component"`
	Meta         MenuTreeMeta `json:"meta"`
}

type ListUserData struct {
	Id         int64  `json:"id"`         // 编号
	UserName   string `json:"name"`       // 用户名
	NickName   string `json:"nickName"`   // 昵称
	Avatar     string `json:"avatar"`     // 头像
	Email      string `json:"email"`      // 邮箱
	Mobile     string `json:"mobile"`     // 手机号
	UserStatus int32  `json:"status"`     // 状态  0：禁用   1：正常
	DeptId     int64  `json:"deptId"`     // 机构ID
	CreateBy   string `json:"createBy"`   // 创建人
	CreateTime string `json:"createTime"` // 创建时间
	UpdateBy   string `json:"updateBy"`   // 更新人
	UpdateTime string `json:"updateTime"` // 更新时间
	DelFlag    int32  `json:"delFlag"`    // 是否删除  0：已删除  1：正常
	JobId      int64  `json:"jobId"`
}

type ListUserReq struct {
	Current  int64  `form:"current,default=1"`
	PageSize int64  `form:"pageSize,default=20"`
	Name     string `form:"name,optional"`
	NickName string `form:"nickName,optional"`
	Mobile   string `form:"mobile,optional"`
	Email    string `form:"email,optional"`
	Status   int32  `form:"status,default=2"`
	DeptId   int64  `form:"deptId,optional"`
	JobId    int64  `form:"deptId,optional"`
}

type ListUserResp struct {
	Code     string          `json:"code"`
	Message  string          `json:"message"`
	Current  int64           `json:"current,default=1"`
	Data     []*ListUserData `json:"data"`
	PageSize int64           `json:"pageSize,default=20"`
	Success  bool            `json:"success"`
	Total    int64           `json:"total"`
}

type LoginData struct {
	AccessToken string `json:"token"`
}

type LoginReq struct {
	Account  string `json:"account"` //手机号或者用户名
	Password string `json:"password"`
}

type LoginResp struct {
	Code    string    `json:"code"`
	Message string    `json:"message"`
	Data    LoginData `json:"data"`
}

type MenuTreeMeta struct {
	Title string `json:"title"`
	Icon  string `json:"icon"`
}

type QueryAllRelationsData struct {
	RoleRelations []*RoleRelations `json:"roleRelations"`
	DeptRelations []*DeptRelations `json:"deptRelations"`
	JobRelations  []*JobRelations  `json:"jobRelations"`
}

type QueryAllRelationsReq struct {
	Current  int64 `form:"current,default=1"`
	PageSize int64 `form:"pageSize,default=20"`
}

type QueryAllRelationsResp struct {
	Code    string                `json:"code"`
	Message string                `json:"message"`
	Data    QueryAllRelationsData `json:"data"`
}

type QueryUserRoleListReq struct {
	UserId   int64  `form:"userId"`
	Current  int64  `form:"current,default=1"`
	PageSize int64  `form:"pageSize,default=20"`
	RoleName string `json:"roleName,optional"` // 角色名称
}

type QueryUserRoleListResp struct {
	Code    string           `json:"code"`
	Message string           `json:"message"`
	Data    UserRoleListData `json:"data"`
}

type ReSetPasswordReq struct {
	Id int64 `json:"id"`
}

type ReSetPasswordResp struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

type RoleListData struct {
	Id         int64  `json:"id"`         // 编号
	Name       string `json:"name"`       // 角色名称
	Remark     string `json:"remark"`     // 备注
	CreateBy   string `json:"createBy"`   // 创建人
	CreateTime string `json:"createTime"` // 创建时间
	UpdateBy   string `json:"updateBy"`   // 更新人
	UpdateTime string `json:"updateTime"` // 更新时间
	DelFlag    int32  `json:"delFlag"`    // 是否删除  0：已删除  1：正常
	Status     int32  `json:"status"`     // 状态
}

type RoleRelations struct {
	Id     int64  `json:"id"`
	Name   string `json:"name"`
	Remark string `json:"remark"`
}

type UpdateUserReq struct {
	Id       int64  `json:"id"`
	Email    string `json:"email"`
	Mobile   string `json:"mobile"`
	Name     string `json:"name"`
	NickName string `json:"nickName"`
	DeptId   int64  `json:"deptId"`
	Status   int32  `json:"status"`
	JobId    int64  `json:"jobId"`
	DelFlag  int64  `json:"delFlag,default=2"` // 是否删除  0：已删除  1：正常
}

type UpdateUserResp struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

type UpdateUserRoleReq struct {
	UserId  int64   `json:"userId"`
	RoleIds []int64 `json:"roleIds"`
}

type UpdateUserRoleResp struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

type UserInfoData struct {
	Avatar      string             `json:"avatar"`
	Name        string             `json:"name"`
	MenuTree    []*ListMenuTree    `json:"menuTree"`
	MenuTreeVue []*ListMenuTreeVue `json:"menuTreeVue"`
}

type UserRoleListData struct {
	RoleList []RoleListData `json:"roleList"`
	RoleIds  []int64        `json:"roleIds"`
}

type UserStatusReq struct {
	Id     int64 `json:"id"`
	Status int32 `json:"status"` // 状态  0：禁用   1：正常
}

type UserStatusResp struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

type UserInfoResp struct {
	Code    string       `json:"code"`
	Message string       `json:"message"`
	Data    UserInfoData `json:"data"`
}
