// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	sysuser "zero-fox-admin/api/admin/internal/handler/sys/user"
	"zero-fox-admin/api/admin/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/UpdateUserStatus",
				Handler: sysuser.UpdateUserStatusHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/addUser",
				Handler: sysuser.AddUserHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/deleteUser",
				Handler: sysuser.DeleteUserHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/info",
				Handler: sysuser.UserInfoHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/queryAllRelations",
				Handler: sysuser.QueryAllRelationsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/queryUserList",
				Handler: sysuser.QueryUserListHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/queryUserRoleList",
				Handler: sysuser.QueryUserRoleListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/reSetPassword",
				Handler: sysuser.ReSetPasswordHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/updateUser",
				Handler: sysuser.UpdateUserHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/updateUserRoleList",
				Handler: sysuser.UpdateUserRoleListHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/sys/user"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/api/sys/user/login",
				Handler: sysuser.UserLoginHandler(serverCtx),
			},
		},
	)
}
